Allow Magic Use: true
Magic Cooldown Time: 2
Casting Requires Permission: false
Allow Self Harm: false
Comet:
  cooldown: 1
Fire Comet:
  cooldown: 1
Dark Pulse:
  cooldown: 1
Escape:
  cooldown: 6
Spirit Fury:
  cooldown: 2
Spiral Cloud Passage:
  cooldown: 3
Floating Passage:
  cooldown: 2
Blood Block:
  cooldown: 0
Blood Explode:
  cooldown: 0
Blood Spark:
  cooldown: 0
Blood Stun:
  cooldown: 0
Blood Wave:
  cooldown: 0
Confuse:
  cooldown: 0
Corrupted Launch:
  cooldown: 0
Corrupted Rain:
  cooldown: 0
Corrupted Shock Wave:
  cooldown: 0
Corrupted Spark:
  cooldown: 0
Corrupted Wave:
  cooldown: 0
Corrupted Wolves:
  cooldown: 0
Dark Aura:
  cooldown: 0
Dark Block:
  cooldown: 0
Dark Circle:
  cooldown: 0
Dark Push:
  cooldown: 0
Dark Spark:
  cooldown: 0
Fire Spark:
  cooldown: 0
Fire Twister:
  cooldown: 0
Flame Shock Wave:
  cooldown: 0
Flame Thrower:
  cooldown: 0
Flame Wave:
  cooldown: 0
Ice Aura:
  cooldown: 0
Freeze:
  cooldown: 0
Launch:
  cooldown: 0
Mephi Aura:
  cooldown: 0
Mephi Away:
  cooldown: 0
Mephi Choke:
  cooldown: 0
Mephi Grab Wave:
  cooldown: 0
Mephi Spark:
  cooldown: 0
Poison Wave:
  cooldown: 0
Magic Spark:
  cooldown: 0
Lightning Arrow:
  cooldown: 0
Thunder Rage:
  cooldown: 0
Thunder Storm:
  cooldown: 0
Thunder Strike:
  cooldown: 0
Spirit Thrust:
  cooldown: 0
One Mind:
  cooldown: 0
Dual Draw:
  cooldown: 0
Whirlwind Slash:
  cooldown: 0
